show auto-load lo
show auto-load loc
show auto-load loca
show auto-load local
show auto-load local-
show auto-load local-g
show auto-load local-gd
show auto-load local-gdb
show auto-load local-gdbi
show auto-load local-gdbin
show auto-load local-gdbini
show auto-load local-gdbinit
