set print frame-a a
set print frame-ar a
set print frame-arg a
set print frame-argu a
set print frame-argum a
set print frame-argume a
set print frame-argumen a
set print frame-argument a
set print frame-arguments a
set print frame-arguments al
set print frame-arguments all
set print frame-arguments s
set print frame-arguments sc
set print frame-arguments sca
set print frame-arguments scal
set print frame-arguments scala
set print frame-arguments scalar
set print frame-arguments scalars
set print frame-arguments n
set print frame-arguments no
set print frame-arguments non
set print frame-arguments none
set print frame-arguments p
set print frame-arguments pr
set print frame-arguments pre
set print frame-arguments pres
set print frame-arguments prese
set print frame-arguments presen
set print frame-arguments presenc
set print frame-arguments presence
