set print re 1
set print rep 1
set print repe 1
set print repea 1
set print repeat 1
set print repeats 1
set print repeats u
set print repeats un
set print repeats unl
set print repeats unli
set print repeats unlim
set print repeats unlimi
set print repeats unlimit
set print repeats unlimite
set print repeats unlimited
