set print se on
set print sev on
set print seve on
set print seven on
set print sevenb on
set print sevenbi on
set print sevenbit on
set print sevenbit- on
set print sevenbit-s on
set print sevenbit-st on
set print sevenbit-str on
set print sevenbit-stri on
set print sevenbit-strin on
set print sevenbit-string on
set print sevenbit-strings on
