set print st on
set print sta on
set print stat on
set print stati on
set print static on
set print static- on
set print static-m on
set print static-me on
set print static-mem on
set print static-memb on
set print static-membe on
set print static-member on
set print static-members on
