set su from to
set sub from to
set subs from to
set subst from to
set substi from to
set substit from to
set substitu from to
set substitut from to
set substitute from to
set substitute- from to
set substitute-p from to
set substitute-pa from to
set substitute-pat from to
set substitute-path from to
