set style address b none
set style address ba none
set style address bac none
set style address back none
set style address backg none
set style address backgr none
set style address backgro none
set style address backgrou none
set style address backgroun none
set style address background none
