set style address i normal
set style address in normal
set style address int normal
set style address inte normal
set style address inten normal
set style address intens normal
set style address intensi normal
set style address intensit normal
set style address intensity normal
