name: Package Extension

on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Package VSCode Extension
        run: npx vsce package
      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v3
        with:
          name: vscode-extension
          path: "*.vsix"
